### ISSUE TITLE
How to debug vsock in host?

### ISSUE THREAD

**Issue by KarthikNedunchezhiyan** [stefano-garzarella/rust-vsock#2]
I tried to test vsock in host machine. Below is the steps i followed

> thread 1:
> vsock.bind(VsockCid::host(), 9001);
> vsock.listen(1024);
> vsock.accept();
> 
> thread 2:
> vsock.connect(VsockCid::host(), 9001)

**error faced:**

> thread 2 exited with error, checked last of error Os{code:22, kind: InvalidInput, message: "Invalid argument"}

**Host environment:**
> VirtualBox 6.1 with nested virtualization
> Ubuntu 18.04.4 LTS

**Other info**

> vsock.connect working fine with firecracker microvm vsock emulation.

Am i missing anything?

edit: Is it possible to listen from host and connect from host?

**Comment by stefano-garzarella** [comment]
Hi @KarthikNedunchezhiyan,
the loopback support (in the host) is really new and it is [added in Linux 5.6](https://stefano-garzarella.github.io/posts/2020-02-20-vsock-nested-vms-loopback/).

I think Ubuntu 18.04 uses an older one.

**Comment by KarthikNedunchezhiyan** [comment]
@stefano-garzarella yes I read about `VMADDR_CID_LOCAL` but it is not available in my host, May I know why above step thrown error. Just curious to know 😃 .

**Comment by stefano-garzarella** [comment]
@KarthikNedunchezhiyan sure :-)

The problem was that before Linux 5.6, the loopback was implemented only in the guest transports for historical reasons (VMware supported only this when vsock was introduced), so in the host it was never implemented and supported, so the connect() return EINVAL, because it was not expected in the host.

If you try in your guest, it should work. For example in a guest with CID 3, you can try:

```
thread 1:
vsock.bind(3, 9001);
vsock.listen(1024);
vsock.accept();

thread 2:
vsock.connect(3, 9001)
```

We received some requests about it and we decided to implement it in Linux 5.6 where your example should work, also using the host CID.

**Comment by KarthikNedunchezhiyan** [comment]
@stefano-garzarella I tried above approach in virtual box, I am getting `AddrNotAvailable` error while binding. I guess guest transport is not loaded in my kernel. Is there any way to find whether vsock guest transport is loaded and load guest transport manually?

**Comment by stefano-garzarella** [comment]
@KarthikNedunchezhiyan the only way is to have a virtio-vsock device attached to your VM.

IIRC virtual box doesn't have it. Can you use libvirt (virsh or virt-manager) with QEMU to run your VM?
If you use virt-manager, you can add vsock device using the GUI.

At that point you can do `lsmod | grep vsock_virtio` to check if the driver is loaded.

**Comment by KarthikNedunchezhiyan** [comment]
@stefano-garzarella tnx for your valuable response 👍
